### ISSUE TITLE
Latest octoprint maintenance branch doesn't work well with this plugin

### ISSUE THREAD

**Issue by pyjamasam** [MoonshineSG/OctoPrint-Autoscroll#1]
Please reference https://github.com/foosel/OctoPrint/issues/1862

It looks like the terminal.scrollToEnd method has changed, and the override in this plugin causes the scrolling to not work as well as expected.

Might be safer to do somthing like references here: http://stackoverflow.com/questions/296667/overriding-a-javascript-function-while-referencing-the-original

So that in the future if the method changes you won't have to update the plugin again.

Glad to test if needed just give me a shout.

**Comment by BillyBlaze** [comment]
Thanks for reporting this to @MoonshineSG 

However we decided to revert the commit that is the culprit of this issue. So it would not require any update from this plugin. The commit also never landed in the OctoPrint PR.

**Comment by MoonshineSG** [comment]
@pyjamasam @BillyBlaze thanks both for the updates. I'll be keeping an eye on this, just in case :D

**Comment by MoonshineSG** [comment]
@pyjamasam I didn't even think anyone is using this plugin.... good to see that i was wrong...

**Comment by foosel** [comment]
Reverted. But in general I'd in fact suggest wrapping original methods instead of outright replacing them, or other kinds of issues might creep up down the line ;)

**Comment by MoonshineSG** [comment]
I'll have a look at it... thanks
